apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-receiver
  labels: 
    app: websocket-receiver
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: websocket-receiver
  template: 
    metadata:
      labels: 
        app: websocket-receiver
    spec: 
      containers:
      - name: websocket-receiver
        image: rlevine1440/websocket-receiver
        ports:
        - containerPort: 8091
        env:
          - name: RABBITMQ_HOST
            valueFrom: 
              secretKeyRef: 
                name: stomp-messagebroker-default-user
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: stomp-messagebroker-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: stomp-messagebroker-default-user
                key: password